/* File: lsodarmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Tue Sep 18 07:37:29 2018
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <setjmp.h>
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *lsodar_error;
static PyObject *lsodar_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
typedef void(*cb_f_in_lsodar__user__routines_typedef)(int *,double *,double *,double *);

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define PRINTPYOBJERR(obj)\
    fprintf(stderr,"lsodar.error is related to ");\
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define SWAP(a,b,t) {\
    t *c;\
    c = a;\
    a = b;\
    b = c;}

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(lsodar_error,errstring);\
        /*goto capi_fail;*/\
    } else 

/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int create_cb_arglist(PyObject* fun,PyTupleObject* xa,const int maxnofargs,const int nofoptargs,int *nofargs,PyTupleObject **args,const char *errmess) {
    PyObject *tmp = NULL;
    PyObject *tmp_fun = NULL;
    int tot,opt,ext,siz,i,di=0;
    CFUNCSMESS("create_cb_arglist\n");
    tot=opt=ext=siz=0;
    /* Get the total number of arguments */
    if (PyFunction_Check(fun))
        tmp_fun = fun;
    else {
        di = 1;
        if (PyObject_HasAttrString(fun,"im_func")) {
            tmp_fun = PyObject_GetAttrString(fun,"im_func");
        }
        else if (PyObject_HasAttrString(fun,"__call__")) {
            tmp = PyObject_GetAttrString(fun,"__call__");
            if (PyObject_HasAttrString(tmp,"im_func"))
                tmp_fun = PyObject_GetAttrString(tmp,"im_func");
            else {
                tmp_fun = fun; /* built-in function */
                tot = maxnofargs;
                if (xa != NULL)
                    tot += PyTuple_Size((PyObject *)xa);
            }
            Py_XDECREF(tmp);
        }
        else if (PyFortran_Check(fun) || PyFortran_Check1(fun)) {
            tot = maxnofargs;
            if (xa != NULL)
                tot += PyTuple_Size((PyObject *)xa);
            tmp_fun = fun;
        }
        else if (F2PyCapsule_Check(fun)) {
            tot = maxnofargs;
            if (xa != NULL)
                ext = PyTuple_Size((PyObject *)xa);
            if(ext>0) {
                fprintf(stderr,"extra arguments tuple cannot be used with CObject call-back\n");
                goto capi_fail;
            }
            tmp_fun = fun;
        }
    }
if (tmp_fun==NULL) {
fprintf(stderr,"Call-back argument must be function|instance|instance.__call__|f2py-function but got %s.\n",(fun==NULL?"NULL":Py_TYPE(fun)->tp_name));
goto capi_fail;
}
#if PY_VERSION_HEX >= 0x03000000
    if (PyObject_HasAttrString(tmp_fun,"__code__")) {
        if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"__code__"),"co_argcount"))
#else
    if (PyObject_HasAttrString(tmp_fun,"func_code")) {
        if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"func_code"),"co_argcount"))
#endif
            tot = PyInt_AsLong(PyObject_GetAttrString(tmp,"co_argcount")) - di;
        Py_XDECREF(tmp);
    }
    /* Get the number of optional arguments */
#if PY_VERSION_HEX >= 0x03000000
    if (PyObject_HasAttrString(tmp_fun,"__defaults__")) {
        if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"__defaults__")))
#else
    if (PyObject_HasAttrString(tmp_fun,"func_defaults")) {
        if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"func_defaults")))
#endif
            opt = PyTuple_Size(tmp);
        Py_XDECREF(tmp);
    }
    /* Get the number of extra arguments */
    if (xa != NULL)
        ext = PyTuple_Size((PyObject *)xa);
    /* Calculate the size of call-backs argument list */
    siz = MIN(maxnofargs+ext,tot);
    *nofargs = MAX(0,siz-ext);
#ifdef DEBUGCFUNCS
    fprintf(stderr,"debug-capi:create_cb_arglist:maxnofargs(-nofoptargs),tot,opt,ext,siz,nofargs=%d(-%d),%d,%d,%d,%d,%d\n",maxnofargs,nofoptargs,tot,opt,ext,siz,*nofargs);
#endif
    if (siz<tot-opt) {
        fprintf(stderr,"create_cb_arglist: Failed to build argument list (siz) with enough arguments (tot-opt) required by user-supplied function (siz,tot,opt=%d,%d,%d).\n",siz,tot,opt);
        goto capi_fail;
    }
    /* Initialize argument list */
    *args = (PyTupleObject *)PyTuple_New(siz);
    for (i=0;i<*nofargs;i++) {
        Py_INCREF(Py_None);
        PyTuple_SET_ITEM((PyObject *)(*args),i,Py_None);
    }
    if (xa != NULL)
        for (i=(*nofargs);i<siz;i++) {
            tmp = PyTuple_GetItem((PyObject *)xa,i-(*nofargs));
            Py_INCREF(tmp);
            PyTuple_SET_ITEM(*args,i,tmp);
        }
    CFUNCSMESS("create_cb_arglist-end\n");
    return 1;
capi_fail:
    if ((PyErr_Occurred())==NULL)
        PyErr_SetString(lsodar_error,errmess);
    return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = lsodar_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
#ifdef __sgi
        *v = PyFloat_AsDouble(obj);
#else
        *v = PyFloat_AS_DOUBLE(obj);
#endif
        return 1;
    }
    tmp = PyNumber_Float(obj);
    if (tmp) {
#ifdef __sgi
        *v = PyFloat_AsDouble(tmp);
#else
        *v = PyFloat_AS_DOUBLE(tmp);
#endif
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = lsodar_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(lsodar,LSODAR)(cb_f_in_lsodar__user__routines_typedef,int*,double*,double*,double*,int*,double*,double*,int*,int*,int*,double*,int*,int*,int*,void*,int*,void*,int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/

/*********************** cb_f_in_lsodar__user__routines ***********************/
PyObject *cb_f_in_lsodar__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_f_in_lsodar__user__routines_args_capi = NULL;
int cb_f_in_lsodar__user__routines_nofargs = 0;
jmp_buf cb_f_in_lsodar__user__routines_jmpbuf;
/*typedef void(*cb_f_in_lsodar__user__routines_typedef)(int *,double *,double *,double *);*/
static void cb_f_in_lsodar__user__routines (int *neq,double *t_cb_capi,double *y,double *e_rwork_lf0_err_cb_capi) {
  PyTupleObject *capi_arglist = cb_f_in_lsodar__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  PyObject *capi_arglist_list = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  double t=(*t_cb_capi);
  double e_rwork_lf0_err=(*e_rwork_lf0_err_cb_capi);
  npy_intp neq_Dims[1] = {-1};
  npy_intp y_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_f_in_lsodar__user__routines (maxnofargs=4(-0))\n");
  CFUNCSMESSPY("cb:cb_f_in_lsodar__user__routines_capi=",cb_f_in_lsodar__user__routines_capi);
  if (cb_f_in_lsodar__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_f_in_lsodar__user__routines_capi = PyObject_GetAttrString(lsodar_module,"f");
  }
  if (cb_f_in_lsodar__user__routines_capi==NULL) {
    PyErr_SetString(lsodar_error,"cb: Callback f not defined (as an argument or module lsodar attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_f_in_lsodar__user__routines_capi)) {
  cb_f_in_lsodar__user__routines_typedef cb_f_in_lsodar__user__routines_cptr;
  cb_f_in_lsodar__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_f_in_lsodar__user__routines_capi);
  (*cb_f_in_lsodar__user__routines_cptr)(neq,t_cb_capi,y,e_rwork_lf0_err_cb_capi);
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(lsodar_module,"f_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(lsodar_error,"Failed to convert lsodar.f_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(lsodar_error,"Callback f argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  neq_Dims[0]=1;
  y_Dims[0]=1;
#ifdef PYPY_VERSION
#define CAPI_ARGLIST_SETITEM(idx, value) PyList_SetItem((PyObject *)capi_arglist_list, idx, value)
  capi_arglist_list = PySequence_List(capi_arglist);
  if (capi_arglist_list == NULL) goto capi_fail;
#else
#define CAPI_ARGLIST_SETITEM(idx, value) PyTuple_SetItem((PyObject *)capi_arglist, idx, value)
#endif
/*pyobjfrom*/
  if (cb_f_in_lsodar__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_INT == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,neq_Dims,NPY_INT,NULL,(char*)neq,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_f_in_lsodar__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_double1(t)))
      goto capi_fail;
  if (cb_f_in_lsodar__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,y_Dims,NPY_DOUBLE,NULL,(char*)y,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_f_in_lsodar__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_double1(e_rwork_lf0_err)))
      goto capi_fail;
#undef CAPI_ARGLIST_SETITEM
#ifdef PYPY_VERSION
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist_list);
#else
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
#endif
  CFUNCSMESS("cb:Call-back calling Python function f.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
#ifdef PYPY_VERSION
  capi_return = PyObject_CallObject(cb_f_in_lsodar__user__routines_capi,(PyObject *)capi_arglist_list);
  Py_DECREF(capi_arglist_list);
  capi_arglist_list = NULL;
#else
  capi_return = PyObject_CallObject(cb_f_in_lsodar__user__routines_capi,(PyObject *)capi_arglist);
#endif
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  CFUNCSMESS("cb:cb_f_in_lsodar__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_f_in_lsodar__user__routines failed.\n");
  Py_XDECREF(capi_return);
  Py_XDECREF(capi_arglist_list);
  if (capi_longjmp_ok)
    longjmp(cb_f_in_lsodar__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/******************* end of cb_f_in_lsodar__user__routines *******************/


/*********************** See f2py2e/rules.py: buildapi ***********************/

/*********************************** lsodar ***********************************/
static char doc_f2py_rout_lsodar_lsodar[] = "\
lsodar(f,neq,y,t,tout,itol,rtol,atol,itask,istate,iopt,rwork,iwork,jac,jt,g,jroot,[lrw,liw,ng,f_extra_args,jac_extra_args,g_extra_args])\n\nWrapper for ``lsodar``.\
\n\nParameters\n----------\n"
"f : call-back function\n"
"neq : input rank-1 array('i') with bounds (1)\n"
"y : input rank-1 array('d') with bounds (1)\n"
"t : input float\n"
"tout : input float\n"
"itol : input int\n"
"rtol : input rank-1 array('d') with bounds (1)\n"
"atol : input rank-1 array('d') with bounds (1)\n"
"itask : input int\n"
"istate : input int\n"
"iopt : input int\n"
"rwork : input rank-1 array('d') with bounds (lrw)\n"
"iwork : input rank-1 array('i') with bounds (liw)\n"
"jac : call-back function\n"
"jt : input int\n"
"g : call-back function\n"
"jroot : input rank-1 array('i') with bounds (ng)\n"
"\nOther Parameters\n----------------\n"
"f_extra_args : input tuple, optional\n    Default: ()\n"
"lrw : input int, optional\n    Default: len(rwork)\n"
"liw : input int, optional\n    Default: len(iwork)\n"
"jac_extra_args : input tuple, optional\n    Default: ()\n"
"g_extra_args : input tuple, optional\n    Default: ()\n"
"ng : input int, optional\n    Default: len(jroot)\n"
"\nNotes\n-----\nCall-back functions::\n\n"
"  def f(neq,t,y,e_rwork_lf0_err): return \n\
  Required arguments:\n"
"    neq : input rank-1 array('i') with bounds (1)\n"
"    t : input float\n"
"    y : input rank-1 array('d') with bounds (1)\n"
"    e_rwork_lf0_err : input float\n"
"#cbdocstr#\n"
"#cbdocstr#";
/* extern void F_FUNC(lsodar,LSODAR)(cb_f_in_lsodar__user__routines_typedef,int*,double*,double*,double*,int*,double*,double*,int*,int*,int*,double*,int*,int*,int*,void*,int*,void*,int*,int*); */
static PyObject *f2py_rout_lsodar_lsodar(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(cb_f_in_lsodar__user__routines_typedef,int*,double*,double*,double*,int*,double*,double*,int*,int*,int*,double*,int*,int*,int*,void*,int*,void*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  PyObject *f_capi = Py_None;
  PyTupleObject *f_xa_capi = NULL;
  PyTupleObject *f_args_capi = NULL;
  int f_nofargs_capi = 0;
  cb_f_in_lsodar__user__routines_typedef f_cptr;
  int *neq = NULL;
  npy_intp neq_Dims[1] = {-1};
  const int neq_Rank = 1;
  PyArrayObject *capi_neq_tmp = NULL;
  int capi_neq_intent = 0;
  PyObject *neq_capi = Py_None;
  double *y = NULL;
  npy_intp y_Dims[1] = {-1};
  const int y_Rank = 1;
  PyArrayObject *capi_y_tmp = NULL;
  int capi_y_intent = 0;
  PyObject *y_capi = Py_None;
  double t = 0;
  PyObject *t_capi = Py_None;
  double tout = 0;
  PyObject *tout_capi = Py_None;
  int itol = 0;
  PyObject *itol_capi = Py_None;
  double *rtol = NULL;
  npy_intp rtol_Dims[1] = {-1};
  const int rtol_Rank = 1;
  PyArrayObject *capi_rtol_tmp = NULL;
  int capi_rtol_intent = 0;
  PyObject *rtol_capi = Py_None;
  double *atol = NULL;
  npy_intp atol_Dims[1] = {-1};
  const int atol_Rank = 1;
  PyArrayObject *capi_atol_tmp = NULL;
  int capi_atol_intent = 0;
  PyObject *atol_capi = Py_None;
  int itask = 0;
  PyObject *itask_capi = Py_None;
  int istate = 0;
  PyObject *istate_capi = Py_None;
  int iopt = 0;
  PyObject *iopt_capi = Py_None;
  double *rwork = NULL;
  npy_intp rwork_Dims[1] = {-1};
  const int rwork_Rank = 1;
  PyArrayObject *capi_rwork_tmp = NULL;
  int capi_rwork_intent = 0;
  PyObject *rwork_capi = Py_None;
  int lrw = 0;
  PyObject *lrw_capi = Py_None;
  int *iwork = NULL;
  npy_intp iwork_Dims[1] = {-1};
  const int iwork_Rank = 1;
  PyArrayObject *capi_iwork_tmp = NULL;
  int capi_iwork_intent = 0;
  PyObject *iwork_capi = Py_None;
  int liw = 0;
  PyObject *liw_capi = Py_None;
  PyObject *jac_capi = Py_None;
  PyTupleObject *jac_xa_capi = NULL;
  PyTupleObject *jac_args_capi = NULL;
  int jac_nofargs_capi = 0;
  jac_typedef jac_cptr;
  int jt = 0;
  PyObject *jt_capi = Py_None;
  PyObject *g_capi = Py_None;
  PyTupleObject *g_xa_capi = NULL;
  PyTupleObject *g_args_capi = NULL;
  int g_nofargs_capi = 0;
  g_typedef g_cptr;
  int ng = 0;
  PyObject *ng_capi = Py_None;
  int *jroot = NULL;
  npy_intp jroot_Dims[1] = {-1};
  const int jroot_Rank = 1;
  PyArrayObject *capi_jroot_tmp = NULL;
  int capi_jroot_intent = 0;
  PyObject *jroot_capi = Py_None;
  static char *capi_kwlist[] = {"f","neq","y","t","tout","itol","rtol","atol","itask","istate","iopt","rwork","iwork","jac","jt","g","jroot","lrw","liw","ng","f_extra_args","jac_extra_args","g_extra_args",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOOOOOO|OOOO!O!O!:lsodar.lsodar",\
    capi_kwlist,&f_capi,&neq_capi,&y_capi,&t_capi,&tout_capi,&itol_capi,&rtol_capi,&atol_capi,&itask_capi,&istate_capi,&iopt_capi,&rwork_capi,&iwork_capi,&jac_capi,&jt_capi,&g_capi,&jroot_capi,&lrw_capi,&liw_capi,&ng_capi,&PyTuple_Type,&f_xa_capi,&PyTuple_Type,&jac_xa_capi,&PyTuple_Type,&g_xa_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable f */
if(F2PyCapsule_Check(f_capi)) {
  f_cptr = F2PyCapsule_AsVoidPtr(f_capi);
} else {
  f_cptr = cb_f_in_lsodar__user__routines;
}

  f_nofargs_capi = cb_f_in_lsodar__user__routines_nofargs;
  if (create_cb_arglist(f_capi,f_xa_capi,4,0,&cb_f_in_lsodar__user__routines_nofargs,&f_args_capi,"failed in processing argument list for call-back f.")) {
    jmp_buf f_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `f`.\n");
    SWAP(f_capi,cb_f_in_lsodar__user__routines_capi,PyObject);
    SWAP(f_args_capi,cb_f_in_lsodar__user__routines_args_capi,PyTupleObject);
    memcpy(&f_jmpbuf,&cb_f_in_lsodar__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable jac */
if(F2PyCapsule_Check(jac_capi)) {
  jac_cptr = F2PyCapsule_AsVoidPtr(jac_capi);
} else {
  jac_cptr = jac;
}

  jac_nofargs_capi = jac_nofargs;
  if (create_cb_arglist(jac_capi,jac_xa_capi,#maxnofargs#,#nofoptargs#,&jac_nofargs,&jac_args_capi,"failed in processing argument list for call-back jac.")) {
    jmp_buf jac_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `jac`.\n");
    SWAP(jac_capi,jac_capi,PyObject);
    SWAP(jac_args_capi,jac_args_capi,PyTupleObject);
    memcpy(&jac_jmpbuf,&jac_jmpbuf,sizeof(jmp_buf));
  /* Processing variable g */
if(F2PyCapsule_Check(g_capi)) {
  g_cptr = F2PyCapsule_AsVoidPtr(g_capi);
} else {
  g_cptr = g;
}

  g_nofargs_capi = g_nofargs;
  if (create_cb_arglist(g_capi,g_xa_capi,#maxnofargs#,#nofoptargs#,&g_nofargs,&g_args_capi,"failed in processing argument list for call-back g.")) {
    jmp_buf g_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `g`.\n");
    SWAP(g_capi,g_capi,PyObject);
    SWAP(g_args_capi,g_args_capi,PyTupleObject);
    memcpy(&g_jmpbuf,&g_jmpbuf,sizeof(jmp_buf));
  /* Processing variable neq */
  neq_Dims[0]=1;
  capi_neq_intent |= F2PY_INTENT_IN;
  capi_neq_tmp = array_from_pyobj(NPY_INT,neq_Dims,neq_Rank,capi_neq_intent,neq_capi);
  if (capi_neq_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(lsodar_error,"failed in converting 2nd argument `neq' of lsodar.lsodar to C/Fortran array" );
  } else {
    neq = (int *)(PyArray_DATA(capi_neq_tmp));

  /* Processing variable itol */
    f2py_success = int_from_pyobj(&itol,itol_capi,"lsodar.lsodar() 6th argument (itol) can't be converted to int");
  if (f2py_success) {
  /* Processing variable itask */
    f2py_success = int_from_pyobj(&itask,itask_capi,"lsodar.lsodar() 9th argument (itask) can't be converted to int");
  if (f2py_success) {
  /* Processing variable istate */
    f2py_success = int_from_pyobj(&istate,istate_capi,"lsodar.lsodar() 10th argument (istate) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iopt */
    f2py_success = int_from_pyobj(&iopt,iopt_capi,"lsodar.lsodar() 11st argument (iopt) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iwork */
  ;
  capi_iwork_intent |= F2PY_INTENT_IN;
  capi_iwork_tmp = array_from_pyobj(NPY_INT,iwork_Dims,iwork_Rank,capi_iwork_intent,iwork_capi);
  if (capi_iwork_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(lsodar_error,"failed in converting 13rd argument `iwork' of lsodar.lsodar to C/Fortran array" );
  } else {
    iwork = (int *)(PyArray_DATA(capi_iwork_tmp));

  /* Processing variable jt */
    f2py_success = int_from_pyobj(&jt,jt_capi,"lsodar.lsodar() 15th argument (jt) can't be converted to int");
  if (f2py_success) {
  /* Processing variable jroot */
  ;
  capi_jroot_intent |= F2PY_INTENT_IN;
  capi_jroot_tmp = array_from_pyobj(NPY_INT,jroot_Dims,jroot_Rank,capi_jroot_intent,jroot_capi);
  if (capi_jroot_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(lsodar_error,"failed in converting 17th argument `jroot' of lsodar.lsodar to C/Fortran array" );
  } else {
    jroot = (int *)(PyArray_DATA(capi_jroot_tmp));

  /* Processing variable y */
  y_Dims[0]=1;
  capi_y_intent |= F2PY_INTENT_IN;
  capi_y_tmp = array_from_pyobj(NPY_DOUBLE,y_Dims,y_Rank,capi_y_intent,y_capi);
  if (capi_y_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(lsodar_error,"failed in converting 3rd argument `y' of lsodar.lsodar to C/Fortran array" );
  } else {
    y = (double *)(PyArray_DATA(capi_y_tmp));

  /* Processing variable t */
    f2py_success = double_from_pyobj(&t,t_capi,"lsodar.lsodar() 4th argument (t) can't be converted to double");
  if (f2py_success) {
  /* Processing variable tout */
    f2py_success = double_from_pyobj(&tout,tout_capi,"lsodar.lsodar() 5th argument (tout) can't be converted to double");
  if (f2py_success) {
  /* Processing variable rtol */
  rtol_Dims[0]=1;
  capi_rtol_intent |= F2PY_INTENT_IN;
  capi_rtol_tmp = array_from_pyobj(NPY_DOUBLE,rtol_Dims,rtol_Rank,capi_rtol_intent,rtol_capi);
  if (capi_rtol_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(lsodar_error,"failed in converting 7th argument `rtol' of lsodar.lsodar to C/Fortran array" );
  } else {
    rtol = (double *)(PyArray_DATA(capi_rtol_tmp));

  /* Processing variable atol */
  atol_Dims[0]=1;
  capi_atol_intent |= F2PY_INTENT_IN;
  capi_atol_tmp = array_from_pyobj(NPY_DOUBLE,atol_Dims,atol_Rank,capi_atol_intent,atol_capi);
  if (capi_atol_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(lsodar_error,"failed in converting 8th argument `atol' of lsodar.lsodar to C/Fortran array" );
  } else {
    atol = (double *)(PyArray_DATA(capi_atol_tmp));

  /* Processing variable rwork */
  ;
  capi_rwork_intent |= F2PY_INTENT_IN;
  capi_rwork_tmp = array_from_pyobj(NPY_DOUBLE,rwork_Dims,rwork_Rank,capi_rwork_intent,rwork_capi);
  if (capi_rwork_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(lsodar_error,"failed in converting 12nd argument `rwork' of lsodar.lsodar to C/Fortran array" );
  } else {
    rwork = (double *)(PyArray_DATA(capi_rwork_tmp));

  /* Processing variable lrw */
  if (lrw_capi == Py_None) lrw = len(rwork); else
    f2py_success = int_from_pyobj(&lrw,lrw_capi,"lsodar.lsodar() 1st keyword (lrw) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(rwork)>=lrw,"len(rwork)>=lrw","1st keyword lrw","lsodar:lrw=%d",lrw) {
  /* Processing variable liw */
  if (liw_capi == Py_None) liw = len(iwork); else
    f2py_success = int_from_pyobj(&liw,liw_capi,"lsodar.lsodar() 2nd keyword (liw) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(iwork)>=liw,"len(iwork)>=liw","2nd keyword liw","lsodar:liw=%d",liw) {
  /* Processing variable ng */
  if (ng_capi == Py_None) ng = len(jroot); else
    f2py_success = int_from_pyobj(&ng,ng_capi,"lsodar.lsodar() 3rd keyword (ng) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(jroot)>=ng,"len(jroot)>=ng","3rd keyword ng","lsodar:ng=%d",ng) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    if ((setjmp(cb_f_in_lsodar__user__routines_jmpbuf)) || (setjmp(jac_jmpbuf)) || (setjmp(g_jmpbuf))) {
      f2py_success = 0;
    } else {
        (*f2py_func)(f_cptr,neq,y,&t,&tout,&itol,rtol,atol,&itask,&istate,&iopt,rwork,&lrw,iwork,&liw,jac_cptr,&jt,g_cptr,&ng,jroot);
    }
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(jroot)>=ng)*/
  } /*if (f2py_success) of ng*/
  /* End of cleaning variable ng */
  } /*CHECKSCALAR(len(iwork)>=liw)*/
  } /*if (f2py_success) of liw*/
  /* End of cleaning variable liw */
  } /*CHECKSCALAR(len(rwork)>=lrw)*/
  } /*if (f2py_success) of lrw*/
  /* End of cleaning variable lrw */
  if((PyObject *)capi_rwork_tmp!=rwork_capi) {
    Py_XDECREF(capi_rwork_tmp); }
  }  /*if (capi_rwork_tmp == NULL) ... else of rwork*/
  /* End of cleaning variable rwork */
  if((PyObject *)capi_atol_tmp!=atol_capi) {
    Py_XDECREF(capi_atol_tmp); }
  }  /*if (capi_atol_tmp == NULL) ... else of atol*/
  /* End of cleaning variable atol */
  if((PyObject *)capi_rtol_tmp!=rtol_capi) {
    Py_XDECREF(capi_rtol_tmp); }
  }  /*if (capi_rtol_tmp == NULL) ... else of rtol*/
  /* End of cleaning variable rtol */
  } /*if (f2py_success) of tout*/
  /* End of cleaning variable tout */
  } /*if (f2py_success) of t*/
  /* End of cleaning variable t */
  if((PyObject *)capi_y_tmp!=y_capi) {
    Py_XDECREF(capi_y_tmp); }
  }  /*if (capi_y_tmp == NULL) ... else of y*/
  /* End of cleaning variable y */
  if((PyObject *)capi_jroot_tmp!=jroot_capi) {
    Py_XDECREF(capi_jroot_tmp); }
  }  /*if (capi_jroot_tmp == NULL) ... else of jroot*/
  /* End of cleaning variable jroot */
  } /*if (f2py_success) of jt*/
  /* End of cleaning variable jt */
  if((PyObject *)capi_iwork_tmp!=iwork_capi) {
    Py_XDECREF(capi_iwork_tmp); }
  }  /*if (capi_iwork_tmp == NULL) ... else of iwork*/
  /* End of cleaning variable iwork */
  } /*if (f2py_success) of iopt*/
  /* End of cleaning variable iopt */
  } /*if (f2py_success) of istate*/
  /* End of cleaning variable istate */
  } /*if (f2py_success) of itask*/
  /* End of cleaning variable itask */
  } /*if (f2py_success) of itol*/
  /* End of cleaning variable itol */
  if((PyObject *)capi_neq_tmp!=neq_capi) {
    Py_XDECREF(capi_neq_tmp); }
  }  /*if (capi_neq_tmp == NULL) ... else of neq*/
  /* End of cleaning variable neq */
    CFUNCSMESS("Restoring jmpbuf for `g`.\n");
    g_capi = g_capi;
    Py_DECREF(g_args_capi);
    g_args_capi = g_args_capi;
    g_nofargs = g_nofargs_capi;
    memcpy(&g_jmpbuf,&g_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable g */
    CFUNCSMESS("Restoring jmpbuf for `jac`.\n");
    jac_capi = jac_capi;
    Py_DECREF(jac_args_capi);
    jac_args_capi = jac_args_capi;
    jac_nofargs = jac_nofargs_capi;
    memcpy(&jac_jmpbuf,&jac_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable jac */
    CFUNCSMESS("Restoring jmpbuf for `f`.\n");
    cb_f_in_lsodar__user__routines_capi = f_capi;
    Py_DECREF(cb_f_in_lsodar__user__routines_args_capi);
    cb_f_in_lsodar__user__routines_args_capi = f_args_capi;
    cb_f_in_lsodar__user__routines_nofargs = f_nofargs_capi;
    memcpy(&cb_f_in_lsodar__user__routines_jmpbuf,&f_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable f */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of lsodar *******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

static FortranDataDef f2py_ls0001_def[] = {
  {"rowns",1,{{209}},NPY_DOUBLE},
  {"ccmax",0,{{-1}},NPY_DOUBLE},
  {"el0",0,{{-1}},NPY_DOUBLE},
  {"h",0,{{-1}},NPY_DOUBLE},
  {"hmin",0,{{-1}},NPY_DOUBLE},
  {"hmxi",0,{{-1}},NPY_DOUBLE},
  {"hu",0,{{-1}},NPY_DOUBLE},
  {"rc",0,{{-1}},NPY_DOUBLE},
  {"tn",0,{{-1}},NPY_DOUBLE},
  {"uround",0,{{-1}},NPY_DOUBLE},
  {"illin",0,{{-1}},NPY_INT},
  {"init",0,{{-1}},NPY_INT},
  {"lyh",0,{{-1}},NPY_INT},
  {"lewt",0,{{-1}},NPY_INT},
  {"lacor",0,{{-1}},NPY_INT},
  {"lsavf",0,{{-1}},NPY_INT},
  {"lwm",0,{{-1}},NPY_INT},
  {"liwm",0,{{-1}},NPY_INT},
  {"mxstep",0,{{-1}},NPY_INT},
  {"mxhnil",0,{{-1}},NPY_INT},
  {"nhnil",0,{{-1}},NPY_INT},
  {"ntrep",0,{{-1}},NPY_INT},
  {"nslast",0,{{-1}},NPY_INT},
  {"nyh",0,{{-1}},NPY_INT},
  {"iowns",1,{{6}},NPY_INT},
  {"icf",0,{{-1}},NPY_INT},
  {"ierpj",0,{{-1}},NPY_INT},
  {"iersl",0,{{-1}},NPY_INT},
  {"jcur",0,{{-1}},NPY_INT},
  {"jstart",0,{{-1}},NPY_INT},
  {"kflag",0,{{-1}},NPY_INT},
  {"l",0,{{-1}},NPY_INT},
  {"meth",0,{{-1}},NPY_INT},
  {"miter",0,{{-1}},NPY_INT},
  {"maxord",0,{{-1}},NPY_INT},
  {"maxcor",0,{{-1}},NPY_INT},
  {"msbp",0,{{-1}},NPY_INT},
  {"mxncf",0,{{-1}},NPY_INT},
  {"n",0,{{-1}},NPY_INT},
  {"nq",0,{{-1}},NPY_INT},
  {"nst",0,{{-1}},NPY_INT},
  {"nfe",0,{{-1}},NPY_INT},
  {"nje",0,{{-1}},NPY_INT},
  {"nqu",0,{{-1}},NPY_INT},
  {NULL}
};
static void f2py_setup_ls0001(char *rowns,char *ccmax,char *el0,char *h,char *hmin,char *hmxi,char *hu,char *rc,char *tn,char *uround,char *illin,char *init,char *lyh,char *lewt,char *lacor,char *lsavf,char *lwm,char *liwm,char *mxstep,char *mxhnil,char *nhnil,char *ntrep,char *nslast,char *nyh,char *iowns,char *icf,char *ierpj,char *iersl,char *jcur,char *jstart,char *kflag,char *l,char *meth,char *miter,char *maxord,char *maxcor,char *msbp,char *mxncf,char *n,char *nq,char *nst,char *nfe,char *nje,char *nqu) {
  int i_f2py=0;
  f2py_ls0001_def[i_f2py++].data = rowns;
  f2py_ls0001_def[i_f2py++].data = ccmax;
  f2py_ls0001_def[i_f2py++].data = el0;
  f2py_ls0001_def[i_f2py++].data = h;
  f2py_ls0001_def[i_f2py++].data = hmin;
  f2py_ls0001_def[i_f2py++].data = hmxi;
  f2py_ls0001_def[i_f2py++].data = hu;
  f2py_ls0001_def[i_f2py++].data = rc;
  f2py_ls0001_def[i_f2py++].data = tn;
  f2py_ls0001_def[i_f2py++].data = uround;
  f2py_ls0001_def[i_f2py++].data = illin;
  f2py_ls0001_def[i_f2py++].data = init;
  f2py_ls0001_def[i_f2py++].data = lyh;
  f2py_ls0001_def[i_f2py++].data = lewt;
  f2py_ls0001_def[i_f2py++].data = lacor;
  f2py_ls0001_def[i_f2py++].data = lsavf;
  f2py_ls0001_def[i_f2py++].data = lwm;
  f2py_ls0001_def[i_f2py++].data = liwm;
  f2py_ls0001_def[i_f2py++].data = mxstep;
  f2py_ls0001_def[i_f2py++].data = mxhnil;
  f2py_ls0001_def[i_f2py++].data = nhnil;
  f2py_ls0001_def[i_f2py++].data = ntrep;
  f2py_ls0001_def[i_f2py++].data = nslast;
  f2py_ls0001_def[i_f2py++].data = nyh;
  f2py_ls0001_def[i_f2py++].data = iowns;
  f2py_ls0001_def[i_f2py++].data = icf;
  f2py_ls0001_def[i_f2py++].data = ierpj;
  f2py_ls0001_def[i_f2py++].data = iersl;
  f2py_ls0001_def[i_f2py++].data = jcur;
  f2py_ls0001_def[i_f2py++].data = jstart;
  f2py_ls0001_def[i_f2py++].data = kflag;
  f2py_ls0001_def[i_f2py++].data = l;
  f2py_ls0001_def[i_f2py++].data = meth;
  f2py_ls0001_def[i_f2py++].data = miter;
  f2py_ls0001_def[i_f2py++].data = maxord;
  f2py_ls0001_def[i_f2py++].data = maxcor;
  f2py_ls0001_def[i_f2py++].data = msbp;
  f2py_ls0001_def[i_f2py++].data = mxncf;
  f2py_ls0001_def[i_f2py++].data = n;
  f2py_ls0001_def[i_f2py++].data = nq;
  f2py_ls0001_def[i_f2py++].data = nst;
  f2py_ls0001_def[i_f2py++].data = nfe;
  f2py_ls0001_def[i_f2py++].data = nje;
  f2py_ls0001_def[i_f2py++].data = nqu;
}
extern void F_FUNC(f2pyinitls0001,F2PYINITLS0001)(void(*)(char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*));
static void f2py_init_ls0001(void) {
  F_FUNC(f2pyinitls0001,F2PYINITLS0001)(f2py_setup_ls0001);
}

static FortranDataDef f2py_lsa001_def[] = {
  {"tsw",0,{{-1}},NPY_DOUBLE},
  {"rowns2",1,{{20}},NPY_DOUBLE},
  {"pdnorm",0,{{-1}},NPY_DOUBLE},
  {"insufr",0,{{-1}},NPY_INT},
  {"insufi",0,{{-1}},NPY_INT},
  {"ixpr",0,{{-1}},NPY_INT},
  {"iowns2",1,{{2}},NPY_INT},
  {"jtyp",0,{{-1}},NPY_INT},
  {"mused",0,{{-1}},NPY_INT},
  {"mxordn",0,{{-1}},NPY_INT},
  {"mxords",0,{{-1}},NPY_INT},
  {NULL}
};
static void f2py_setup_lsa001(char *tsw,char *rowns2,char *pdnorm,char *insufr,char *insufi,char *ixpr,char *iowns2,char *jtyp,char *mused,char *mxordn,char *mxords) {
  int i_f2py=0;
  f2py_lsa001_def[i_f2py++].data = tsw;
  f2py_lsa001_def[i_f2py++].data = rowns2;
  f2py_lsa001_def[i_f2py++].data = pdnorm;
  f2py_lsa001_def[i_f2py++].data = insufr;
  f2py_lsa001_def[i_f2py++].data = insufi;
  f2py_lsa001_def[i_f2py++].data = ixpr;
  f2py_lsa001_def[i_f2py++].data = iowns2;
  f2py_lsa001_def[i_f2py++].data = jtyp;
  f2py_lsa001_def[i_f2py++].data = mused;
  f2py_lsa001_def[i_f2py++].data = mxordn;
  f2py_lsa001_def[i_f2py++].data = mxords;
}
extern void F_FUNC(f2pyinitlsa001,F2PYINITLSA001)(void(*)(char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*));
static void f2py_init_lsa001(void) {
  F_FUNC(f2pyinitlsa001,F2PYINITLSA001)(f2py_setup_lsa001);
}

static FortranDataDef f2py_lsr001_def[] = {
  {"rownr3",1,{{2}},NPY_DOUBLE},
  {"t0",0,{{-1}},NPY_DOUBLE},
  {"tlast",0,{{-1}},NPY_DOUBLE},
  {"toutc",0,{{-1}},NPY_DOUBLE},
  {"lg0",0,{{-1}},NPY_INT},
  {"lg1",0,{{-1}},NPY_INT},
  {"lgx",0,{{-1}},NPY_INT},
  {"iownr3",1,{{2}},NPY_INT},
  {"irfnd",0,{{-1}},NPY_INT},
  {"itaskc",0,{{-1}},NPY_INT},
  {"ngc",0,{{-1}},NPY_INT},
  {"nge",0,{{-1}},NPY_INT},
  {NULL}
};
static void f2py_setup_lsr001(char *rownr3,char *t0,char *tlast,char *toutc,char *lg0,char *lg1,char *lgx,char *iownr3,char *irfnd,char *itaskc,char *ngc,char *nge) {
  int i_f2py=0;
  f2py_lsr001_def[i_f2py++].data = rownr3;
  f2py_lsr001_def[i_f2py++].data = t0;
  f2py_lsr001_def[i_f2py++].data = tlast;
  f2py_lsr001_def[i_f2py++].data = toutc;
  f2py_lsr001_def[i_f2py++].data = lg0;
  f2py_lsr001_def[i_f2py++].data = lg1;
  f2py_lsr001_def[i_f2py++].data = lgx;
  f2py_lsr001_def[i_f2py++].data = iownr3;
  f2py_lsr001_def[i_f2py++].data = irfnd;
  f2py_lsr001_def[i_f2py++].data = itaskc;
  f2py_lsr001_def[i_f2py++].data = ngc;
  f2py_lsr001_def[i_f2py++].data = nge;
}
extern void F_FUNC(f2pyinitlsr001,F2PYINITLSR001)(void(*)(char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*,char*));
static void f2py_init_lsr001(void) {
  F_FUNC(f2pyinitlsr001,F2PYINITLSR001)(f2py_setup_lsr001);
}

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"lsodar",-1,{{-1}},0,(char *)F_FUNC(lsodar,LSODAR),(f2py_init_func)f2py_rout_lsodar_lsodar,doc_f2py_rout_lsodar_lsodar},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "lsodar",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_lsodar(void) {
#else
#define RETVAL
PyMODINIT_FUNC initlsodar(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = lsodar_module = PyModule_Create(&moduledef);
#else
  m = lsodar_module = Py_InitModule("lsodar", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module lsodar (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'lsodar' is auto-generated with f2py (version:2).\nFunctions:\n"
"  lsodar(f,neq,y,t,tout,itol,rtol,atol,itask,istate,iopt,rwork,iwork,jac,jt,g,jroot,lrw=len(rwork),liw=len(iwork),ng=len(jroot),f_extra_args=(),jac_extra_args=(),g_extra_args=())\n"
"COMMON blocks:\n""  /ls0001/ rowns(209),ccmax,el0,h,hmin,hmxi,hu,rc,tn,uround,illin,init,lyh,lewt,lacor,lsavf,lwm,liwm,mxstep,mxhnil,nhnil,ntrep,nslast,nyh,iowns(6),icf,ierpj,iersl,jcur,jstart,kflag,l,meth,miter,maxord,maxcor,msbp,mxncf,n,nq,nst,nfe,nje,nqu\n""  /lsa001/ tsw,rowns2(20),pdnorm,insufr,insufi,ixpr,iowns2(2),jtyp,mused,mxordn,mxords\n""  /lsr001/ rownr3(2),t0,tlast,toutc,lg0,lg1,lgx,iownr3(2),irfnd,itaskc,ngc,nge\n"".");
  PyDict_SetItemString(d, "__doc__", s);
  lsodar_error = PyErr_NewException ("lsodar.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

  F2PyDict_SetItemString(d, "ls0001", PyFortranObject_New(f2py_ls0001_def,f2py_init_ls0001));
  F2PyDict_SetItemString(d, "lsa001", PyFortranObject_New(f2py_lsa001_def,f2py_init_lsa001));
  F2PyDict_SetItemString(d, "lsr001", PyFortranObject_New(f2py_lsr001_def,f2py_init_lsr001));
/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"lsodar");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
