C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pyinitls0001(setupfunc)
      external setupfunc
      double precision rowns(209)
      double precision ccmax
      double precision el0
      double precision h
      double precision hmin
      double precision hmxi
      double precision hu
      double precision rc
      double precision tn
      double precision uround
      integer illin
      integer init
      integer lyh
      integer lewt
      integer lacor
      integer lsavf
      integer lwm
      integer liwm
      integer mxstep
      integer mxhnil
      integer nhnil
      integer ntrep
      integer nslast
      integer nyh
      integer iowns(6)
      integer icf
      integer ierpj
      integer iersl
      integer jcur
      integer jstart
      integer kflag
      integer l
      integer meth
      integer miter
      integer maxord
      integer maxcor
      integer msbp
      integer mxncf
      integer n
      integer nq
      integer nst
      integer nfe
      integer nje
      integer nqu
      common /ls0001/ rowns,ccmax,el0,h,hmin,hmxi,hu,rc,tn,uround,
     &illin,init,lyh,lewt,lacor,lsavf,lwm,liwm,mxstep,mxhnil,nhnil,ntrep
     &,nslast,nyh,iowns,icf,ierpj,iersl,jcur,jstart,kflag,l,meth,miter,m
     &axord,maxcor,msbp,mxncf,n,nq,nst,nfe,nje,nqu
      call setupfunc(rowns,ccmax,el0,h,hmin,hmxi,hu,rc,tn,uround,i
     &llin,init,lyh,lewt,lacor,lsavf,lwm,liwm,mxstep,mxhnil,nhnil,ntrep,
     &nslast,nyh,iowns,icf,ierpj,iersl,jcur,jstart,kflag,l,meth,miter,ma
     &xord,maxcor,msbp,mxncf,n,nq,nst,nfe,nje,nqu)
      end

      subroutine f2pyinitlsa001(setupfunc)
      external setupfunc
      double precision tsw
      double precision rowns2(20)
      double precision pdnorm
      integer insufr
      integer insufi
      integer ixpr
      integer iowns2(2)
      integer jtyp
      integer mused
      integer mxordn
      integer mxords
      common /lsa001/ tsw,rowns2,pdnorm,insufr,insufi,ixpr,iowns2,
     &jtyp,mused,mxordn,mxords
      call setupfunc(tsw,rowns2,pdnorm,insufr,insufi,ixpr,iowns2,j
     &typ,mused,mxordn,mxords)
      end

      subroutine f2pyinitlsr001(setupfunc)
      external setupfunc
      double precision rownr3(2)
      double precision t0
      double precision tlast
      double precision toutc
      integer lg0
      integer lg1
      integer lgx
      integer iownr3(2)
      integer irfnd
      integer itaskc
      integer ngc
      integer nge
      common /lsr001/ rownr3,t0,tlast,toutc,lg0,lg1,lgx,iownr3,irf
     &nd,itaskc,ngc,nge
      call setupfunc(rownr3,t0,tlast,toutc,lg0,lg1,lgx,iownr3,irfn
     &d,itaskc,ngc,nge)
      end


